my_robot:

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 10

  joint_1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_1
    pid: {p: 10.0, i: 0.1, d: 1.0}
    
  joint_2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_2
    pid: {p: 10.0, i: 0.1, d: 1.0}
